#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REVIEW_DOC="$ROOT_DIR/docs/OPENFPGA_GENESIS_PRIORITY1_CLOCKING_REVIEW.md"
TIMING_DOC="$ROOT_DIR/docs/OPENFPGA_GENESIS_TIMING_REVIEW_BLOCKER_ORDER.md"
POST_GATE_DOC="$ROOT_DIR/docs/OPENFPGA_GENESIS_POST_FITTER_GATE.md"
OUT="$ROOT_DIR/docs/OPENFPGA_GENESIS_PRIORITY1_CLOCKING_GATE.md"
NOW="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"

for file in "$REVIEW_DOC" "$POST_GATE_DOC"; do
  if [[ ! -f "$file" ]]; then
    echo "Missing required source file: $file" >&2
    exit 1
  fi
done

rel_path() {
  local path="$1"
  if [[ "$path" == "$ROOT_DIR"* ]]; then
    echo "${path#$ROOT_DIR/}"
  else
    echo "$path"
  fi
}

priority1_items="$(rg -m1 'total priority1 review items:' "$REVIEW_DOC" | sed -E 's/.*: *([0-9]+).*/\1/' || true)"
if [[ -z "$priority1_items" ]]; then
  priority1_items="$(rg -c '^- total instances:' "$REVIEW_DOC" 2>/dev/null || true)"
fi
if [[ -z "$priority1_items" ]]; then
  priority1_items=999
fi

priority1_has_blocking=0
if rg -q 'status: blocks timing/assembler gate' "$REVIEW_DOC"; then
  priority1_has_blocking=1
fi

priority1_has_review=0
if rg -q 'status: needs review before timing gate' "$REVIEW_DOC"; then
  priority1_has_review=1
fi

if [[ "$priority1_items" == "999" ]]; then
  gate_decision="PRIORITY1_CLOCKING_REVIEW_STILL_REQUIRED"
else
  if (( priority1_items > 0 )); then
    if (( priority1_has_blocking == 1 )); then
      gate_decision="PRIORITY1_CLOCKING_BLOCKED"
    else
      gate_decision="PRIORITY1_CLOCKING_REVIEW_STILL_REQUIRED"
    fi
  else
    gate_decision="PRIORITY1_CLOCKING_REVIEW_STILL_REQUIRED"
  fi
fi

if [[ -f "$TIMING_DOC" ]]; then
  existing_timing_count="$(rg -m1 '^active_timing_blocker_count:' "$TIMING_DOC" | awk -F: '{print $2}' | tr -dc '0-9' || true)"
fi

{
  echo "# openFPGA Genesis Priority-1 clocking gate"
  echo "Generated: $NOW"
  echo
  echo "## Inputs"
  echo "- Priority-1 clocking review: $(rel_path "$REVIEW_DOC")"
  echo "- Post-fitter gate decision: $(rel_path "$POST_GATE_DOC")"
  if [[ -f "$TIMING_DOC" ]]; then
    echo "- Timing blocker order doc: $(rel_path "$TIMING_DOC")"
  fi
  echo
  echo "## Current priority1 gate decision"
  echo "Current priority1 gate decision: **$gate_decision**"
  echo
  echo "## Evidence"
  echo "Priority-1 review item count (from review doc): ${priority1_items}"
  if [[ -n "${existing_timing_count:-}" ]]; then
    echo "Active timing blocker count from timing-order doc: $existing_timing_count"
  fi
  echo
  echo "## Scope constraints for this task"
  echo "- fitter: not run by this review path"
  echo "- assembler: not run by this review path"
  echo "- timing: not run by this review path"
  echo "- bitstream: not generated by this review path"
  echo "- APF packaging: not run"
  echo "- runtime boot/correctness: not claimed"
  echo
  if [[ "$gate_decision" == "PRIORITY1_CLOCKING_BLOCKED" ]]; then
    echo "## Gate rationale"
    echo "- One or more Priority-1 clocking issues remain and must be reviewed before timing-only advancement."
    echo "- No timing-gate handoff recommendation from this script unless count is zero by explicit manual override."
  else
    echo "## Gate rationale"
    echo "- No immediate Priority-1 count has been confirmed in review output."
    echo "- Review handoff remains conservative until an explicit timing-review checkpoint is approved."
    echo "- No functional/runtime claim is made in this gate."
  fi
} > "$OUT"

echo "Wrote $(rel_path "$OUT")"
