#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAP_LOG="$ROOT_DIR/docs/OPENFPGA_GENESIS_FITTER_SMOKE_MAP_LOG.txt"
FIT_LOG="$ROOT_DIR/docs/OPENFPGA_GENESIS_FITTER_SMOKE_FIT_LOG.txt"
REVIEW_DOC="$ROOT_DIR/docs/OPENFPGA_GENESIS_FITTER_UNKNOWN_WARNING_REVIEW.md"
MAP_LOG_REL="docs/OPENFPGA_GENESIS_FITTER_SMOKE_MAP_LOG.txt"
FIT_LOG_REL="docs/OPENFPGA_GENESIS_FITTER_SMOKE_FIT_LOG.txt"
QSF="third_party/openFPGA-Genesis/src/fpga/ap_core.qsf"
APF_TOP="third_party/openFPGA-Genesis/src/fpga/apf/apf_top.v"
CORE_TOP="third_party/openFPGA-Genesis/src/fpga/core/core_top.sv"
CORE_BRIDGE="third_party/openFPGA-Genesis/src/fpga/core/core_bridge_cmd.v"
NOW="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"

for file in "$MAP_LOG" "$FIT_LOG" "$QSF" "$APF_TOP" "$CORE_TOP" "$CORE_BRIDGE"; do
  if [[ ! -f "$file" ]]; then
    echo "Missing required file: $file"
    exit 1
  fi
  done

count_code() {
  local code="$1"
  rg -c "Warning \(${code}\)" "$MAP_LOG" "$FIT_LOG" | awk -F: '{s += $2} END {print s+0}'
}

sample_code() {
  local code="$1"
  rg -m 1 "Warning \(${code}\)" "$MAP_LOG" "$FIT_LOG" 2>/dev/null | sed -e "s#^$ROOT_DIR/##" || true
}

warn_nocode_key() {
  local line="$1"
  local lower
  lower="$(printf '%s' "$line" | tr 'A-Z' 'a-z')"

  if [[ "$lower" == *"rst port on the pll is not properly connected"* ]]; then
    echo "PLL_RESET_NOT_CONNECTED"
    return
  fi
  if [[ "$lower" == *"incomplete i/o assignments"* ]]; then
    echo "INCOMPLETE_IO_ASSIGNMENTS"
    return
  fi
  if [[ "$lower" == *"non-dedicated"* ]]; then
    echo "NON_DEDICATED_CLOCK_ROUTING"
    return
  fi
  if [[ "$lower" == *"ignoring some wildcard destinations"* ]]; then
    echo "IGNORED_FAST_IO_WILDCARD"
    return
  fi
  if [[ "$lower" == *"no output enable"* ]]; then
    echo "NO_OUTPUT_ENABLE"
    return
  fi
  if [[ "$lower" == *"no output dependent on input pin"* ]]; then
    echo "PIN_ASSIGNMENT_WARNING"
    return
  fi
  if [[ "$lower" == *"placement effort multiplier"* ]]; then
    echo "PLACEMENT_ROUTING_WARNING"
    return
  fi

  echo "NO_CODE_WARNING"
}

count_nocode_warning() {
  local line
  local class
  local total=0

  for file in "$MAP_LOG" "$FIT_LOG"; do
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      [[ "$line" == *"Info:"* ]] && continue
      [[ "$line" != *"Warning:"* ]] && continue
      [[ "$line" == *"Warning ("* ]] && continue
      class="$(warn_nocode_key "$line")"
      if [[ "$class" == "NO_CODE_WARNING" ]]; then
        total=$((total + 1))
      fi
    done < "$file"
  done

  echo "$total"
}

sample_nocode_warning() {
  local line
  local class

  for file in "$MAP_LOG" "$FIT_LOG"; do
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      [[ "$line" == *"Info:"* ]] && continue
      [[ "$line" != *"Warning:"* ]] && continue
      [[ "$line" == *"Warning ("* ]] && continue
      class="$(warn_nocode_key "$line")"
      if [[ "$class" == "NO_CODE_WARNING" ]]; then
        echo "$line"
        return
      fi
    done < "$file"
  done

  echo ""
}

source_ref() {
  local pattern="$1"
  local file="$2"
  rg -n -F "${pattern}" "$file" | head -n 1 | sed -E 's/:/ line:/' | sed -e "s#^$ROOT_DIR/##"
}

emit() {
  local class="$1"
  local count="$2"
  local sample="$3"
  local source_ref="$4"
  local disposition="$5"
  local rationale="$6"
  local next_action="$7"

  count="${count:-0}"

  echo "### REVIEW_ENTRY class=${class}"
  echo "- count: ${count}"
  [[ -n "$sample" ]] && echo "- sample: ${sample}"
  [[ -n "$source_ref" ]] && echo "- source: ${source_ref}"
  echo "- disposition: ${disposition}"
  echo "- rationale: ${rationale}"
  echo "- next_action: ${next_action}"
  echo
}

: > "$REVIEW_DOC"
{
  echo "# openFPGA Genesis fitter unknown warning review"
  echo "Generated: $NOW"
  echo "Scope: post-fitter warning class review only; no Quartus run."
  echo "Inputs checked:"
  echo "- ${MAP_LOG_REL}"
  echo "- ${FIT_LOG_REL}"
  echo "- third_party/openFPGA-Genesis/src/fpga/ap_core.qsf"
  echo "- third_party/openFPGA-Genesis/src/fpga/apf/apf_top.v"
  echo "- third_party/openFPGA-Genesis/src/fpga/core/core_top.sv"
  echo "- third_party/openFPGA-Genesis/src/fpga/core/core_bridge_cmd.v"
  echo

  echo "## Unknown warning classes"
  emit CODE_13009 "$(count_code 13009)" "$(sample_code 13009)" "" "needs_review" "OpenFPGA ties and I/O controls produce this tri-state warning class in this scaffold state. This is expected for fixed translator behavior and must be confirmed against the final APF pin map." "Keep this as needs-review before timing gate and confirm source intent."
  emit CODE_13010 "$(count_code 13010)" "$(sample_code 13010)" "" "needs_review" "DDIO helper nodes are generated by Quartus primitives and tied by inout handling. This warning is not a blocker for smoke but needs APF-level review." "Keep as needs-review and re-evaluate after final pin strategy is locked."
  emit CODE_13024 "$(count_code 13024)" "$(sample_code 13024)" "" "needs_review" "Output constant nodes are mostly associated with scaffolded unused I/O and intentionally fixed pins." "Confirm each constanted pin is expected before moving into timing."
  emit CODE_13032 "$(count_code 13032)" "$(sample_code 13032)" "" "needs_review" "Tri-state nodes fed by constants are usually from fixed-direction inout translation in scaffold ports." "Keep as needs-review before timing."
  emit CODE_13033 "$(count_code 13033)" "$(sample_code 13033)" "$(source_ref 'cart_tran_bank0[4]' "$CORE_TOP")" "needs_review" "Cartridge port bus pins are deliberately preloaded/fixed in scaffold. This class is expected but requires explicit review against APF design constraints." "Validate pin plan before timing gate and keep as review item."
  emit CODE_13039 "$(count_code 13039)" "$(sample_code 13039)" "" "needs_review" "Bidirectional pins with explicit constant/z behavior in top-level stubs trigger this class." "Review every bidirectional pin mapping before timing."
  emit CODE_13040 "$(count_code 13040)" "$(sample_code 13040)" "$(source_ref 'aux_sda' "$APF_TOP")" "needs_review" "RFU/unused I2C lines are intentionally left with no driver in this scaffold." "Do not enable these paths; keep as needs-review placeholder for this milestone."
  emit CODE_13410 "$(count_code 13410)" "$(sample_code 13410)" "$(source_ref 'cart_tran_bank0_dir\|cart_tran_bank2_dir\|cart_tran_bank3_dir\|cart_tran_bank1_dir\|cart_tran_pin30_dir\|cart_pin30_pwroff_reset\|cart_tran_pin31_dir' "$CORE_TOP")" "needs_review" "Direction outputs are tied constants for cartridge/pin-control behavior in the inherited APF template." "Keep as needs-review before timing review gate."
  emit CODE_14284 "$(count_code 14284)" "$(sample_code 14284)" "$(source_ref 'synthesized away' "$CORE_TOP")" "safe" "Synthesized-away nodes are mostly in unused or optimized paths in this scaffold." "No gate impact in this milestone; confirm with future functional expansion."
  emit CODE_14285 "$(count_code 14285)" "$(sample_code 14285)" "$(source_ref 'synthesized away' "$CORE_TOP")" "safe" "Synthesized-away RAM nodes are consistent with inactive scaffold memory paths." "No action for warning-only smoke milestone."
  emit CODE_14320 "$(count_code 14320)" "$(sample_code 14320)" "" "safe" "Synthesized-away node warnings are expected when unused blocks in the scaffold are optimized away." "Track the class during later active memory enabling and keep non-blocking classification now."
  emit CODE_15610 "$(count_code 15610)" "$(sample_code 15610)" "$(source_ref 'No output dependent on input pin' "$APF_TOP")" "needs_review" "No-output-dependent pin warnings are expected with feature-deferred APF ports and must be reconciled before timing review." "Track each pin against final feature plan before advancing."
  emit CODE_15714 "$(count_code 15714)" "$(sample_code 15714)" "" "needs_review" "Incomplete I/O assignments are present from a reduced-feature top-level. This does not block this scaffold, but is timing-review sensitive." "Close only after I/O constraints are fully assigned for enabled feature set."
  emit CODE_16406 "$(count_code 16406)" "$(sample_code 16406)" "$(source_ref 'clk_74b' "$QSF")" "needs_review" "Non-dedicated clock routing warning was observed and is expected for current scaffold routing." "Require timing-review justification before gate transition."
  emit CODE_16407 "$(count_code 16407)" "$(sample_code 16407)" "$(source_ref 'clk_74b' "$QSF")" "needs_review" "Detail warning on REFCLK input placement confirms non-dedicated clock handling and should be reviewed together with clock constraints." "Keep as timing-review caution."
  emit CODE_169064 "$(count_code 169064)" "$(sample_code 169064)" "$(source_ref 'No output enable' "$APF_TOP")" "needs_review" "Output enable behavior is tied to fixed stubbed paths and will become active as more features are enabled." "Keep as timing-review caution only."
  emit CODE_170136 "$(count_code 170136)" "$(sample_code 170136)" "" "needs_review" "Placement effort multiplier warning is not a blocker for this scaffold but is relevant for timing closure stability." "Record as timing-review watch item before next gate."
  emit CODE_176251 "$(count_code 176251)" "$(sample_code 176251)" "$(source_ref 'FAST_OUTPUT_REGISTER' "$QSF")" "needs_review" "Wildcard destination behavior is intentional only with explicit plan; requires review for final clocking and timing." "Keep as requires-review before timing gate."
  emit CODE_19016 "$(count_code 19016)" "$(sample_code 19016)" "$(source_ref 'reg current_pix_clk' "$CORE_TOP")" "needs_review" "Clock mux exists in current pixel path and should be verified before timing closure." "Keep review item and confirm constraints on clock muxing."
  emit CODE_19017 "$(count_code 19017)" "$(sample_code 19017)" "$(source_ref 'current_pix_clk' "$CORE_TOP")" "needs_review" "Named clock multiplexer should be verified against final timing constraints." "Do not force timing-gate readiness until source review and timing evidence are added."
  emit CODE_21074 "$(count_code 21074)" "$(sample_code 21074)" "$(source_ref 'No output dependent on input pin' "$CORE_TOP")" "needs_review" "Several top-level inputs are intentionally unconnected in this scaffold." "Track these inputs in pin-audit before timing review."
  emit CODE_287013 "$(count_code 287013)" "$(sample_code 287013)" "" "safe" "Generated RAM primitive warning for unused/underdriven node names is consistent with current scaffold paths." "No action before timing because this is not a direct functional blocker."
  no_code_warning_count="$(count_nocode_warning)"
  no_code_warning_sample="$(sample_nocode_warning)"
  if [[ "$no_code_warning_count" -gt 0 ]]; then
    emit NO_CODE_WARNING "$no_code_warning_count" "$no_code_warning_sample" "" "unknown" "These lines did not match any known non-code warning class mapping and remain unreviewed non-code warnings." "Classify each remaining non-code warning line before moving into timing review."
  else
    emit NO_CODE_WARNING "0" "" "" "safe" "No-code warning-like lines are mapped to known classes or do not exist." "No additional no-code action needed."
  fi

  echo "## Timing-review warning classes"
  emit IGNORED_FAST_IO_WILDCARD "$(count_code 176251)" "$(sample_code 176251)" "$(source_ref 'FAST_OUTPUT_REGISTER' "$QSF")" "needs_review" "Wildcard destination behavior is intentional only with explicit plan; requires review for final clocking and timing." "Keep as requires-review before timing gate."
  emit INCOMPLETE_IO_ASSIGNMENTS "$(count_code 15714)" "$(sample_code 15714)" "" "needs_review" "Feature-reduced scaffold leaves some optional I/O unassigned." "Address only when corresponding feature ports are enabled."
  emit NON_DEDICATED_CLOCK_ROUTING "$(count_code 16406)" "$(sample_code 16406)" "$(source_ref 'clk_74b' "$QSF")" "needs_review" "Non-dedicated clock routing was observed in logs and needs explicit timing review before gating to timing step." "Hold this as needs-review before timing gate and document any accepted constraints."
  emit NO_OUTPUT_ENABLE "$(count_code 169064)" "$(sample_code 169064)" "$(source_ref 'No output dependent on input pin' "$APF_TOP")" "needs_review" "Output-enable behavior is tied to fixed-port stubs and generated memory signals in this scaffold." "Keep as timing-review caution until full I/O behavior is validated."
  emit PIN_ASSIGNMENT_WARNING "$(count_code 15610)" "$(sample_code 15610)" "$(source_ref 'No output dependent on input pin' "$APF_TOP")" "needs_review" "Core I/O ports with tied-off behavior generate this warning class with reduced feature scope." "Only advance timing after final input/output assignment map is approved."
  emit PLACEMENT_ROUTING_WARNING "$(count_code 170136)" "$(sample_code 170136)" "" "needs_review" "Placement effort multiplier is not a blocking warning but is timing-context sensitive." "Treat as timing-review note, not as blocker."
  emit PLL_RESET_NOT_CONNECTED "$(rg -c 'RST port on the PLL is not properly connected' "$FIT_LOG" || true)" "$(rg -m 1 'RST port on the PLL is not properly connected' "$FIT_LOG" || true)" "$(source_ref 'rst      ( 0' "$CORE_TOP")" "needs_review" "The PLL reset pin is fixed to zero in openFPGA template instantiation in this milestone; behavior is intentional but should be explicitly reviewed for timing/recovery." "Keep as needs-review until reset behavior is documented for next task."

  echo
  echo "## Summary"
  echo
  echo "### Class decision guidance for classifier integration"
  echo "- CODE_14320 / CODE_14284 / CODE_14285 / CODE_287013: safe / known inherited"
  echo "- CODE_10259 / CODE_292013: accepted smoke-only risk"
  echo "- CODE_13009 / 13010 / 13024 / 13032 / 13033 / 13039 / 13040 / 13410 / 15610 / 15714 / 16406 / 16407 / 169064 / 170136 / 176251 / 19016 / 19017 / 21074 / NO_CODE_WARNING / IGNORED_FAST_IO_WILDCARD / INCOMPLETE_IO_ASSIGNMENTS / NON_DEDICATED_CLOCK_ROUTING / NO_OUTPUT_ENABLE / PIN_ASSIGNMENT_WARNING / PLACEMENT_ROUTING_WARNING / PLL_RESET_NOT_CONNECTED: needs_review"
  echo "- CODE_10030 / CODE_10036 / CODE_10230 / CODE_10762 / CODE_10858 / CODE_113027 / CODE_113028 / CODE_12241: accepted from existing 7P safe/inherited categorization unless overridden later"

  echo
  echo "REVIEW_ENTRY class=CODE_13009 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_13010 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_13024 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_13032 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_13033 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_13039 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_13040 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_13410 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_14284 reviewed=true disposition=safe"
  echo "REVIEW_ENTRY class=CODE_14285 reviewed=true disposition=safe"
  echo "REVIEW_ENTRY class=CODE_14320 reviewed=true disposition=safe"
  echo "REVIEW_ENTRY class=CODE_15610 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_15714 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_16406 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_16407 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_169064 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_170136 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_176251 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_19016 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_19017 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_21074 reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_287013 reviewed=true disposition=safe"
  if [[ "${no_code_warning_count:-0}" -gt 0 ]]; then
    echo "REVIEW_ENTRY class=NO_CODE_WARNING reviewed=true disposition=unknown"
  else
    echo "REVIEW_ENTRY class=NO_CODE_WARNING reviewed=true disposition=safe"
  fi
  echo "REVIEW_ENTRY class=IGNORED_FAST_IO_WILDCARD reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=INCOMPLETE_IO_ASSIGNMENTS reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=NON_DEDICATED_CLOCK_ROUTING reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=NO_OUTPUT_ENABLE reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=PIN_ASSIGNMENT_WARNING reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=PLACEMENT_ROUTING_WARNING reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=PLL_RESET_NOT_CONNECTED reviewed=true disposition=needs_review"
  echo "REVIEW_ENTRY class=CODE_10259 reviewed=true disposition=accepted_smoke_only"
  echo "REVIEW_ENTRY class=CODE_292013 reviewed=true disposition=accepted_smoke_only"
} > "$REVIEW_DOC"

echo "Wrote: $REVIEW_DOC"
